/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts.index'
import { Route as AuthenticatedContractsNewRouteImport } from './routes/_authenticated/contracts.new'
import { Route as AuthenticatedContractsIdRouteImport } from './routes/_authenticated/contracts.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/_authenticated/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/_authenticated/contracts/',
    path: '/contracts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContractsNewRoute =
  AuthenticatedContractsNewRouteImport.update({
    id: '/_authenticated/contracts/new',
    path: '/contracts/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedContractsIdRoute =
  AuthenticatedContractsIdRouteImport.update({
    id: '/_authenticated/contracts/$id',
    path: '/contracts/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/_authenticated/contracts/new': typeof AuthenticatedContractsNewRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/'
    | '/contracts/$id'
    | '/contracts/new'
    | '/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/contracts/$id' | '/contracts/new' | '/contracts'
  id:
    | '__root__'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/contracts/$id'
    | '/_authenticated/contracts/new'
    | '/_authenticated/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContractsIdRoute: typeof AuthenticatedContractsIdRoute
  AuthenticatedContractsNewRoute: typeof AuthenticatedContractsNewRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts/new': {
      id: '/_authenticated/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof AuthenticatedContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contracts/$id': {
      id: '/_authenticated/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AuthenticatedContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContractsIdRoute: AuthenticatedContractsIdRoute,
  AuthenticatedContractsNewRoute: AuthenticatedContractsNewRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
