/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedCarreteirosRouteImport } from './routes/_authenticated/carreteiros'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedAlcadasRouteImport } from './routes/_authenticated/alcadas'
import { Route as AuthenticatedSolicitacoesIndexRouteImport } from './routes/_authenticated/solicitacoes.index'
import { Route as AuthenticatedMedicoesIndexRouteImport } from './routes/_authenticated/medicoes.index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts.index'
import { Route as AuthenticatedSolicitacoesNewRouteImport } from './routes/_authenticated/solicitacoes.new'
import { Route as AuthenticatedMedicoesNewRouteImport } from './routes/_authenticated/medicoes.new'
import { Route as AuthenticatedContractsNewRouteImport } from './routes/_authenticated/contracts.new'
import { Route as AuthenticatedContractsIdRouteImport } from './routes/_authenticated/contracts.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarreteirosRoute =
  AuthenticatedCarreteirosRouteImport.update({
    id: '/carreteiros',
    path: '/carreteiros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlcadasRoute = AuthenticatedAlcadasRouteImport.update({
  id: '/alcadas',
  path: '/alcadas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitacoesIndexRoute =
  AuthenticatedSolicitacoesIndexRouteImport.update({
    id: '/solicitacoes/',
    path: '/solicitacoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicoesIndexRoute =
  AuthenticatedMedicoesIndexRouteImport.update({
    id: '/medicoes/',
    path: '/medicoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitacoesNewRoute =
  AuthenticatedSolicitacoesNewRouteImport.update({
    id: '/solicitacoes/new',
    path: '/solicitacoes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicoesNewRoute =
  AuthenticatedMedicoesNewRouteImport.update({
    id: '/medicoes/new',
    path: '/medicoes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsNewRoute =
  AuthenticatedContractsNewRouteImport.update({
    id: '/contracts/new',
    path: '/contracts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIdRoute =
  AuthenticatedContractsIdRouteImport.update({
    id: '/contracts/$id',
    path: '/contracts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alcadas': typeof AuthenticatedAlcadasRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/carreteiros': typeof AuthenticatedCarreteirosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/medicoes/new': typeof AuthenticatedMedicoesNewRoute
  '/solicitacoes/new': typeof AuthenticatedSolicitacoesNewRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/medicoes/': typeof AuthenticatedMedicoesIndexRoute
  '/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alcadas': typeof AuthenticatedAlcadasRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/carreteiros': typeof AuthenticatedCarreteirosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/contracts/new': typeof AuthenticatedContractsNewRoute
  '/medicoes/new': typeof AuthenticatedMedicoesNewRoute
  '/solicitacoes/new': typeof AuthenticatedSolicitacoesNewRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/medicoes': typeof AuthenticatedMedicoesIndexRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alcadas': typeof AuthenticatedAlcadasRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/carreteiros': typeof AuthenticatedCarreteirosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/contracts/$id': typeof AuthenticatedContractsIdRoute
  '/_authenticated/contracts/new': typeof AuthenticatedContractsNewRoute
  '/_authenticated/medicoes/new': typeof AuthenticatedMedicoesNewRoute
  '/_authenticated/solicitacoes/new': typeof AuthenticatedSolicitacoesNewRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/medicoes/': typeof AuthenticatedMedicoesIndexRoute
  '/_authenticated/solicitacoes/': typeof AuthenticatedSolicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alcadas'
    | '/cadastros'
    | '/carreteiros'
    | '/financeiro'
    | '/historico'
    | '/settings'
    | '/contracts/$id'
    | '/contracts/new'
    | '/medicoes/new'
    | '/solicitacoes/new'
    | '/contracts/'
    | '/medicoes/'
    | '/solicitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alcadas'
    | '/cadastros'
    | '/carreteiros'
    | '/financeiro'
    | '/historico'
    | '/settings'
    | '/'
    | '/contracts/$id'
    | '/contracts/new'
    | '/medicoes/new'
    | '/solicitacoes/new'
    | '/contracts'
    | '/medicoes'
    | '/solicitacoes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alcadas'
    | '/_authenticated/cadastros'
    | '/_authenticated/carreteiros'
    | '/_authenticated/financeiro'
    | '/_authenticated/historico'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/contracts/$id'
    | '/_authenticated/contracts/new'
    | '/_authenticated/medicoes/new'
    | '/_authenticated/solicitacoes/new'
    | '/_authenticated/contracts/'
    | '/_authenticated/medicoes/'
    | '/_authenticated/solicitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carreteiros': {
      id: '/_authenticated/carreteiros'
      path: '/carreteiros'
      fullPath: '/carreteiros'
      preLoaderRoute: typeof AuthenticatedCarreteirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alcadas': {
      id: '/_authenticated/alcadas'
      path: '/alcadas'
      fullPath: '/alcadas'
      preLoaderRoute: typeof AuthenticatedAlcadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/': {
      id: '/_authenticated/solicitacoes/'
      path: '/solicitacoes'
      fullPath: '/solicitacoes/'
      preLoaderRoute: typeof AuthenticatedSolicitacoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicoes/': {
      id: '/_authenticated/medicoes/'
      path: '/medicoes'
      fullPath: '/medicoes/'
      preLoaderRoute: typeof AuthenticatedMedicoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes/new': {
      id: '/_authenticated/solicitacoes/new'
      path: '/solicitacoes/new'
      fullPath: '/solicitacoes/new'
      preLoaderRoute: typeof AuthenticatedSolicitacoesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicoes/new': {
      id: '/_authenticated/medicoes/new'
      path: '/medicoes/new'
      fullPath: '/medicoes/new'
      preLoaderRoute: typeof AuthenticatedMedicoesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/new': {
      id: '/_authenticated/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof AuthenticatedContractsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$id': {
      id: '/_authenticated/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AuthenticatedContractsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlcadasRoute: typeof AuthenticatedAlcadasRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedCarreteirosRoute: typeof AuthenticatedCarreteirosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContractsIdRoute: typeof AuthenticatedContractsIdRoute
  AuthenticatedContractsNewRoute: typeof AuthenticatedContractsNewRoute
  AuthenticatedMedicoesNewRoute: typeof AuthenticatedMedicoesNewRoute
  AuthenticatedSolicitacoesNewRoute: typeof AuthenticatedSolicitacoesNewRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedMedicoesIndexRoute: typeof AuthenticatedMedicoesIndexRoute
  AuthenticatedSolicitacoesIndexRoute: typeof AuthenticatedSolicitacoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlcadasRoute: AuthenticatedAlcadasRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedCarreteirosRoute: AuthenticatedCarreteirosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContractsIdRoute: AuthenticatedContractsIdRoute,
  AuthenticatedContractsNewRoute: AuthenticatedContractsNewRoute,
  AuthenticatedMedicoesNewRoute: AuthenticatedMedicoesNewRoute,
  AuthenticatedSolicitacoesNewRoute: AuthenticatedSolicitacoesNewRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedMedicoesIndexRoute: AuthenticatedMedicoesIndexRoute,
  AuthenticatedSolicitacoesIndexRoute: AuthenticatedSolicitacoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
